version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
  weather-exporter:
    image: weather-exporter:latest
    container_name: weather-exporter
    environment:
      - KEY=${KEY}
      - CITY=Tallinn
    ports:
      - "9500:9500"
