global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "weather-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["10.0.2.4:9500"]
